/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encodeSync(input: Buffer, windowSize: number, lookaheadSize: number): Buffer
export function decodeSync(input: Buffer, windowSize: number, lookaheadSize: number): Buffer
export function encode(input: Buffer, windowSize: number, lookaheadSize: number, signal?: AbortSignal | undefined | null): Promise<Buffer>
export function decode(input: Buffer, windowSize: number, lookaheadSize: number, signal?: AbortSignal | undefined | null): Promise<Buffer>
