/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encodeSync(input: Buffer, windowSize: number, lookaheadSize: number): Buffer
export declare function decodeSync(input: Buffer, windowSize: number, lookaheadSize: number, outputBufferSize?: number | undefined | null): Buffer
export declare function encode(input: Buffer, windowSize: number, lookaheadSize: number, signal?: AbortSignal | undefined | null): Promise<Buffer>
export declare function decode(input: Buffer, windowSize: number, lookaheadSize: number, signal?: AbortSignal | undefined | null, outputBufferSize?: number | undefined | null): Promise<Buffer>
